/*
Como conectar ventanas en netbeans java.cc
https://www.youtube.com/watch?v=Ha6YBbK65XI
Para inicio de sesion:
http://pharalax.com/blog/java-y-netbeans-i-formulario-de-login/
 */
package interfaces;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author arielp
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemVerClientes = new javax.swing.JMenuItem();
        jMenuItemNuevoCliente = new javax.swing.JMenuItem();
        jMenuMercaderias = new javax.swing.JMenu();
        jMenuItemVerMercaderias = new javax.swing.JMenuItem();
        jMenuItemNuevaMercaderia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuClientes.setText("Clientes");

        jMenuItemVerClientes.setText("Ver Todos");
        jMenuItemVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemVerClientes);

        jMenuItemNuevoCliente.setText("Nuevo Cliente");
        jMenuItemNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemNuevoCliente);

        jMenuBar1.add(jMenuClientes);

        jMenuMercaderias.setText("Mercaderias");

        jMenuItemVerMercaderias.setText("Ver Mercaderias");
        jMenuItemVerMercaderias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerMercaderiasActionPerformed(evt);
            }
        });
        jMenuMercaderias.add(jMenuItemVerMercaderias);

        jMenuItemNuevaMercaderia.setText("Nueva Mercaderia");
        jMenuItemNuevaMercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaMercaderiaActionPerformed(evt);
            }
        });
        jMenuMercaderias.add(jMenuItemNuevaMercaderia);

        jMenuBar1.add(jMenuMercaderias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerClientesActionPerformed
        System.out.println("Click en Ver todos los clientes");
        if (this.listadoClientes == null) {
            listadoClientes = new ListadoClientes();
            listadoClientes.setBounds(10, 10, 500, 500);
            listadoClientes.setVisible(true);
            this.add(listadoClientes);
    }//GEN-LAST:event_jMenuItemVerClientesActionPerformed
    }
    private void itemVerMercaderiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerMercaderiasActionPerformed

        if (this.listadoMercaderias == null) {
            this.listadoMercaderias = new ListadoMercaderias();
            listadoMercaderias.setBounds(10, 10, 500, 500);
            listadoMercaderias.setVisible(true);
            this.add(listadoMercaderias);
        }
        try {
            this.nuevaMercaderia.setClosed(true);
            this.nuevoCliente.setClosed(true);
            
        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_itemVerMercaderiasActionPerformed

    private void jMenuItemNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoClienteActionPerformed
        if (this.nuevoCliente == null) {
            nuevoCliente = new NuevoCliente();
            nuevoCliente.setBounds(10, 10, 500, 500);
            nuevoCliente.setVisible(true);
            this.add(nuevoCliente);
    }//GEN-LAST:event_jMenuItemNuevoClienteActionPerformed
    }

    private void jMenuItemNuevaMercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaMercaderiaActionPerformed
        if (this.nuevaMercaderia == null) {
            this.nuevaMercaderia = new NuevaMercaderia();
            nuevaMercaderia.setBounds(10, 10, 400, 500);
            nuevaMercaderia.setVisible(true);
            this.add(nuevaMercaderia);
        }

//        NuevaMercaderia nuevaMercaderia = new NuevaMercaderia();
//        nuevaMercaderia.setBounds(10, 10, 400, 500);
//        this.add(nuevaMercaderia);
//        nuevaMercaderia.setVisible(true);

    }//GEN-LAST:event_jMenuItemNuevaMercaderiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenuItem jMenuItemNuevaMercaderia;
    private javax.swing.JMenuItem jMenuItemNuevoCliente;
    private javax.swing.JMenuItem jMenuItemVerClientes;
    private javax.swing.JMenuItem jMenuItemVerMercaderias;
    private javax.swing.JMenu jMenuMercaderias;
    // End of variables declaration//GEN-END:variables

    private NuevoCliente nuevoCliente;
    private NuevaMercaderia nuevaMercaderia;
    private ListadoMercaderias listadoMercaderias;
    private ListadoClientes listadoClientes;
}
